version: '3.9'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: zsce_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-zsce}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-zsce_password}
      POSTGRES_DB: ${POSTGRES_DB:-zsce}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
